version: "3.1"
services:
  jenkins:
    build: ./
    container_name: 'jenkins2'
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      main:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3360:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=123456
      - MYSQL_USER=zhangpei
    networks:
      main:
networks:
  main:
